#!/bin/bash
yum install -y httpd
sudo systemctl enable httpd
sudo systemctl start httpd
sudo amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
sudo systemctl stop httpd
sudo systemctl start httpd
